version: 2.1
jobs:
  build_test:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test renderer process
          command: yarn test.renderer
workflows:
  build-and-test:
    jobs:
      - build_test
