version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Test renderer process
          command: yarn test.renderer
workflows:
  build-and-test:
    jobs:
      - build-and-test
