version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build project
          command: yarn package
      - run:
          name: Test main process
          command: yarn test.main
      - run:
          name: Test renderer process
          command: yarn test.renderer
workflows:
  build-and-test:
    jobs:
      - build_test
